### ISSUE TITLE
A question about test

### ISSUE THREAD

**Issue by yansuoyuli** [mazpie/genrl#3]
Thanks for your awesome work! I wonder how to get the test result in the paper. Thanks.
<img width="776" alt="截屏2024-11-26 17 30 34" src="https://github.com/user-attachments/assets/184af983-671e-4225-a5b1-1d4254ef16b0">

**Comment by mazpie** [comment]
Hi @yansuoyuli,

Thank you for your interest.

Please, see the section [Behavior Learning](https://github.com/mazpie/genrl?tab=readme-ov-file#behavior-learning) on the README.

Agents are periodically evaluated when you run the code to train the behavior in imagination. The plots on the paper compare the performance when the training is complete.

**Comment by yansuoyuli** [comment]
Hello! When I run the code to train the behavior in the stickman walk task, it outputs the following metrics as follows:

{"train/imag_actor_loss": -0.7295766472816467, "train/imag_actor_grad_norm": 1.1113815307617188, "train/imag_critic_loss": 0.38500282168388367, "train/imag_critic_grad_norm": 0.030712738633155823, "train/imag_reward_mean": 0.48301538825035095, "train/imag_reward_std": 0.20098361372947693, "train/imag_reward_normed_mean": 0.48301538825035095, "train/imag_reward_normed_std": 0.20098361372947693, "train/imag_critic_slow": 57.531070709228516, "train/imag_critic_target": 57.482696533203125, "train/imag_normed_target_mean": 0.7133544087409973, "train/imag_normed_target_std": 0.33899185061454773, "train/imag_reward_ema_005": 54.521183013916016, "train/imag_reward_ema_095": 58.67271423339844, "train/imag_actor_ent": -8.1666898727417, "train/imag_actor_ent_scale": 0.0, "train/imag_critic": 57.48235321044922, "train/fps": 3.659556365325872, "train/step": 50000.0, "train/frame": 100000, "_timestamp": 1733053491.7366998, "_runtime": 10930.786888837814, "_step": 61, "eval/episode_reward": 53.82664219435584, "eval/episode_length": 1000.0, "eval/episode": 0.0, "eval/step": 50000.0, "eval/frame": 100000, "best_episode": {"_type": "video-file", "sha256": "cb7e927e1a8607ca8a05ce091bea7c2a71add270efdc5d364311c0fa69b74e7d", "size": 2206270, "path": "media/videos/best_episode_58_cb7e927e1a8607ca8a05.gif", "width": 64, "height": 64}, "worst_episode": {"_type": "video-file", "sha256": "b92c0ee2661e8aa47f5c7a8d2772b34fa53fb52f94f04f7bdcf2ac28068e4e24", "size": 2216326, "path": "media/videos/worst_episode_59_b92c0ee2661e8aa47f5c.gif", "width": 64, "height": 64}, "_wandb": {"runtime": 10931}}


I wonder how to get the episodic rewards, which it seems to be 53.82664219435584, which is different in the paper.
Thanks!

**Comment by yansuoyuli** [comment]
I also use the pretrained model provided by the code. The result also differs from the performance shown in the paper:
{"train/imag_actor_loss": -0.6631203889846802, "train/imag_actor_grad_norm": 1.959341287612915, "train/imag_critic_loss": 0.52336186170578, "train/imag_critic_grad_norm": 0.051519863307476044, "train/imag_reward_mean": 0.35826748609542847, "train/imag_reward_std": 0.17386916279792786, "train/imag_reward_normed_mean": 0.35826748609542847, "train/imag_reward_normed_std": 0.17386916279792786, "train/imag_critic_slow": 47.72933578491211, "train/imag_critic_target": 47.69749069213867, "train/imag_normed_target_mean": 0.6482250690460205, "train/imag_normed_target_std": 0.318576455116272, "train/imag_reward_ema_005": 44.069183349609375, "train/imag_reward_ema_095": 49.66647720336914, "train/imag_actor_ent": -8.357023239135742, "train/imag_actor_ent_scale": 0.0, "train/imag_critic": 47.702693939208984, "train/fps": 3.668291163992254, "train/step": 50000.0, "train/frame": 100000, "_timestamp": 1733053415.3118718, "_runtime": 10988.624908685684, "_step": 61, "eval/episode_reward": 394.9013274955595, "eval/episode_length": 1000.0, "eval/episode": 0.0, "eval/step": 50000.0, "eval/frame": 100000, "best_episode": {"_type": "video-file", "sha256": "cbdddb313d420702609b8b0c7988fe80019e005b1432d701b0c26aa1381f1b8b", "size": 2229441, "path": "media/videos/best_episode_58_cbdddb313d420702609b.gif", "width": 64, "height": 64}, "worst_episode": {"_type": "video-file", "sha256": "efe48b6d68a4e46cdeb030e35dac9a24d542864234cea1f8eef56fc3831a9e37", "size": 2185301, "path": "media/videos/worst_episode_59_efe48b6d68a4e46cdeb0.gif", "width": 64, "height": 64}, "_wandb": {"runtime": 10989}}

Here the score seems to be 394.9013274955595
